import {
	Accessibility,
	Activity,
	BadgeCent,
	BadgeDollarSign,
	BadgeEuro,
	BadgeIndianRupee,
	BadgeJapaneseYen,
	BadgePercent,
	BadgePoundSterling,
	BadgeRussianRuble,
	BadgeSwissFranc,
	BadgeTurkishLira,
	Dumbbell,
	Gift,
	Hamburger,
	Heart,
	Landmark,
	Wallet,
} from 'lucide-react'

export const CATEGORY_ICONS = [
	{ id: 'badge-cent', icon: BadgeCent, category: 'Finances' },
	{ id: 'badge-dollar-sign', icon: BadgeDollarSign, category: 'Finances' },
	{ id: 'badge-euro', icon: BadgeEuro, category: 'Finances' },
	{ id: 'badge-indian-rupee', icon: BadgeIndianRupee, category: 'Finances' },
	{ id: 'badge-japanese-yen', icon: BadgeJapaneseYen, category: 'Finances' },
	{ id: 'badge-percent', icon: BadgePercent, category: 'Finances' },
	{ id: 'badge-pound-sterling', icon: BadgePoundSterling, category: 'Finances' },
	{ id: 'badge-russian-ruble', icon: BadgeRussianRuble, category: 'Finances' },
	{ id: 'badge-swiss-franc', icon: BadgeSwissFranc, category: 'Finances' },
	{ id: 'badge-turkish-lira', icon: BadgeTurkishLira, category: 'Finances' },
	{ id: 'wallet', icon: Wallet, category: 'Finances' },
	{ id: 'landmark', icon: Landmark, category: 'Finances' },
	{ id: 'accessibility', icon: Accessibility, category: 'Health' },
	{ id: 'activity', icon: Activity, category: 'Health' },
	{ id: 'heart', icon: Heart, category: 'Health' },
	{ id: 'gift', icon: Gift, category: 'Accounts' },
	{ id: 'hamburger', icon: Hamburger, category: 'Food' },
	{ id: 'dumbbell', icon: Dumbbell, category: 'Sports' },
]
