import {
	Accessibility,
	Activity,
	Apple,
	Armchair,
	Award,
	BadgeCent,
	BadgeEuro,
	BadgePoundSterling,
	Banana,
	Banknote,
	Bed,
	Beef,
	Birdhouse,
	Bitcoin,
	Bolt,
	Bone,
	BottleWine,
	BrushCleaning,
	Cigarette,
	CircleStar,
	Cookie,
	CookingPot,
	CreditCard,
	DollarSign,
	Dumbbell,
	Egg,
	Fan,
	Gem,
	Gift,
	Grape,
	Hamburger,
	Hammer,
	HandFist,
	Heart,
	Hospital,
	IceCreamCone,
	Lamp,
	Landmark,
	LandPlot,
	Medal,
	Pill,
	PillBottle,
	Pizza,
	Siren,
	SquareStar,
	Tablets,
	Trophy,
	Volleyball,
	Wallet,
	WavesLadder,
} from 'lucide-react'

export const CATEGORY_ICONS = [
	{ id: 'badge-cent', icon: BadgeCent, category: 'Finances' },
	{ id: 'badge-euro', icon: BadgeEuro, category: 'Finances' },
	{ id: 'badge-pound-sterling', icon: BadgePoundSterling, category: 'Finances' },
	{ id: 'banknote', icon: Banknote, category: 'Finances' },
	{ id: 'wallet', icon: Wallet, category: 'Finances' },
	{ id: 'landmark', icon: Landmark, category: 'Finances' },
	{ id: 'bitcoin', icon: Bitcoin, category: 'Finances' },
	{ id: 'dollar-sign', icon: DollarSign, category: 'Finances' },
	{ id: 'credit-card', icon: CreditCard, category: 'Finances' },
	{ id: 'gem', icon: Gem, category: 'Finances' },
	{ id: 'accessibility', icon: Accessibility, category: 'Health' },
	{ id: 'activity', icon: Activity, category: 'Health' },
	{ id: 'heart', icon: Heart, category: 'Health' },
	{ id: 'hospital', icon: Hospital, category: 'Health' },
	{ id: 'pill', icon: Pill, category: 'Health' },
	{ id: 'cigarette', icon: Cigarette, category: 'Health' },
	{ id: 'siren', icon: Siren, category: 'Health' },
	{ id: 'pill-bottle', icon: PillBottle, category: 'Health' },
	{ id: 'tablets', icon: Tablets, category: 'Health' },
	{ id: 'bone', icon: Bone, category: 'Health' },
	{ id: 'gift', icon: Gift, category: 'Accounts' },
	{ id: 'armchair', icon: Armchair, category: 'Accounts' },
	{ id: 'bed', icon: Bed, category: 'Accounts' },
	{ id: 'birdhouse', icon: Birdhouse, category: 'Accounts' },
	{ id: 'bolt', icon: Bolt, category: 'Accounts' },
	{ id: 'brush-cleaning', icon: BrushCleaning, category: 'Accounts' },
	{ id: 'cooking-pot', icon: CookingPot, category: 'Accounts' },
	{ id: 'lamp', icon: Lamp, category: 'Accounts' },
	{ id: 'hammer', icon: Hammer, category: 'Accounts' },
	{ id: 'fan', icon: Fan, category: 'Accounts' },
	{ id: 'hamburger', icon: Hamburger, category: 'Food' },
	{ id: 'apple', icon: Apple, category: 'Food' },
	{ id: 'banana', icon: Banana, category: 'Food' },
	{ id: 'beef', icon: Beef, category: 'Food' },
	{ id: 'bottle-wine', icon: BottleWine, category: 'Food' },
	{ id: 'egg', icon: Egg, category: 'Food' },
	{ id: 'grape', icon: Grape, category: 'Food' },
	{ id: 'pizza', icon: Pizza, category: 'Food' },
	{ id: 'ice-cream-cone', icon: IceCreamCone, category: 'Food' },
	{ id: 'cookie', icon: Cookie, category: 'Food' },
	{ id: 'dumbbell', icon: Dumbbell, category: 'Sports' },
	{ id: 'award', icon: Award, category: 'Sports' },
	{ id: 'circle-star', icon: CircleStar, category: 'Sports' },
	{ id: 'waves-ladder', icon: WavesLadder, category: 'Sports' },
	{ id: 'hand-fist', icon: HandFist, category: 'Sports' },
	{ id: 'land-plot', icon: LandPlot, category: 'Sports' },
	{ id: 'medal', icon: Medal, category: 'Sports' },
	{ id: 'square-star', icon: SquareStar, category: 'Sports' },
	{ id: 'trophy', icon: Trophy, category: 'Sports' },
	{ id: 'volleyball', icon: Volleyball, category: 'Sports' },
]
